# General example for adding mounts to CAS workers
# PatchTransformer
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: data-mounts-cas
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: access-clients
      mountPath: "/access-clients"
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
     name: access-clients
     nfs:
       path: /nfs/aks-pv/access-clients
       server: 10.0.0.7
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: shared-data
      mountPath: "/nfs/shared"
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
     name: shared-data
     nfs:
       path: /nfs/aks-pv/shared
       server: 10.0.0.7
target:
  kind: CASDeployment
  annotationSelector: sas.com/sas-access-config=true