# General example for adding mounts to SAS containers with a 
# PatchTransformer
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: compute-server-mount-nfs-home
patch: |-
  - op: add
    path: /template/spec/containers/0/volumeMounts/-
    value:
      name: nfs-home
      mountPath: /nfs/home
  - op: add
    path: /template/spec/volumes/-
    value:
     name: nfs-home
     nfs:
       path: /nfs/home
       server: 10.0.0.7
target:
  kind: PodTemplate
  name: sas-compute-job-config