---
config:
  application:
    sas.logon.initial:
      user: sasboot
      password: Orion123
    sas.identities.providers.ldap.connection:
      host: 10.0.0.6
      password: Orion123
      port: 389
      url: ldap://${sas.identities.providers.ldap.connection.host}:${sas.identities.providers.ldap.connection.port}
      userDN: cn=ldapreader,ou=SpecialAccounts,ou=aom,dc=aom,dc=dk
    sas.identities.providers.ldap.group:
      baseDN: ou=Groups,ou=aom,dc=aom,dc=dk
    sas.identities.providers.ldap.user:
      baseDN: ou=Users,ou=aom,dc=aom,dc=dk
    sas.identities:
      administrator: aomsbe
